services:
  mysql:
    image: mysql:8.0  # Puedes cambiar la versi칩n si es necesario
    container_name: my_mysql_db
    restart: unless-stopped  # Asegura que se reinicie solo si falla
    environment:
      MYSQL_ROOT_PASSWORD: root  # Cambia esta contrase침a por seguridad
      MYSQL_DATABASE: mydata        # Nombre de la base de datos por defecto
      MYSQL_USER: user                 # Usuario personalizado
      MYSQL_PASSWORD: password          # Contrase침a del usuario
    ports:
      - "3307:3306"  # Mapea el puerto 3306 del contenedor al host
    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d  # Scripts de inicializaci칩n
    networks:
      - mysql_network

volumes:
  mysql_data:  # Volumen persistente para la base de datos

networks:
  mysql_network:
    driver: bridge
